project_id = "ppduheroaoklcusdrlzt"

[functions.chat-with-iasted]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.get-realtime-token]
verify_jwt = true

[functions.auth-pin-login]
verify_jwt = false

[functions.send-official-correspondence]
verify_jwt = true

[functions.document-ocr]
verify_jwt = true

[functions.security-alert-login]
verify_jwt = true

[functions.new-device-alert]
verify_jwt = true

[functions.semantic-search-kb]
verify_jwt = true

[functions.generate-kb-embeddings]
verify_jwt = true
