project_id = "ppduheroaoklcusdrlzt"

[functions.chat-with-iasted]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-realtime-token]
verify_jwt = true

[functions.auth-pin-login]
verify_jwt = false

[functions.send-official-correspondence]
verify_jwt = true

[functions.document-ocr]
verify_jwt = true
